version: 2.1

orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  test:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install

      - run:
          name: Install dependencies
          command: sudo apt-get -y install xvfb vim-gtk3
      - run:
          name: Which (g)vim?
          command: xvfb-run gvim --version

      - run:
          name: Run tests
          command: xvfb-run bundle exec rspec spec

workflows:
  test:
    jobs: [test]
